stages:
  - build

build-backend:
  stage: build
  image: maven:3.9-eclipse-temurin-17
  script:
    - echo "=== Début du build du Backend Java ==="
    - cd mainframe-api
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - mainframe-api/target/*.jar
    expire_in: 1 hour

build-frontend:
  stage: build
  image: node:20-alpine
  script:
    - echo "=== Début du build du Frontend Angular ==="
    - cd mainframe-ui
    - npm install
    - npm run build -- --configuration production
  artifacts:
    paths:
      - mainframe-ui/dist/
    expire_in: 1 hour
